services:
  JmsWorker:

jobs:
  hot.plate:
    job: HotPlate
    cron: '0 1 8 * * ? *'
    singleton: true

queues:
  /queues/warmup_request:
  /queues/feed_changed:

messaging:
  /queues/warmup_request: HotPlate
  /queues/feed_changed: FeedUpdateWhiteboard

