# The test environment should require minimal configuration, and is the one targeted by travis.
# Avoid creating too many dependencies (if any) on a test.local.yml
canvas_proxy:
  fake: true

# To avoid "Illegal key size" errors on systems which we can't modify (e.g., Travis),
# lower the security of the encryption algorithm.
oauth2:
  encryption: "aes-128-cbc"
